### ISSUE TITLE
mu4e~compose-browse-url-mail doesn't handle Cc and Bcc

### ISSUE THREAD

**Issue by amosbird** [djcb/mu#1025]
```
(mu4e~compose-browse-url-mail "mailto:bogus@email.com?cc=bogus2@snail-mail.com&amp;bcc=fake@spam.com")
```
doesn't fill the Cc and Bcc fields.

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> (mu4e~compose-browse-url-mail "mailto:bogus@email.com?cc=bogus2@snail-mail.com&amp;bcc=fake@spam.com")
>
> doesn't fill the Cc and Bcc fields.

find-file-at-point is doing this, but it doesn't handle "&amp;". If it
can help, I fixed this in helm with `helm-html-decode-entities-string`
which is a function in helm-utils.el.
So doing C-x C-f RET with helm on such url is composing a mail with Cc
and Bcc.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by amosbird** [comment]
cool, thanks

**Comment by amosbird** [comment]
Hmm, I just tested the helm files patch. It still doesn't work.

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> Hmm, I just tested the helm files patch. It still doesn't work.

Assume C-x C-f is bound to helm-find-files, if you put cursor on your
url below and hit C-x C-f RET
"mailto:bogus@email.com?cc=bogus2@snail-mail.com&amp;bcc=fake@spam.com"
You will have a mail buffer with the correct Cc and Bcc.
Ensure you have updated helm to commit b035b10f otherwise you will endup
with "&amp;" not translated.

However this is not fixing `mu4e~compose-browse-url-mail` which should
behave similarly, I just mentionned that the helm code is working as
expected hooping it can help fixing this.

Here a patch fixing `mu4e~compose-browse-url-mail` but not fixing
entities (you need a function similar to
`helm-html-decode-entities-string` to transform url):

diff --git a/mu4e/mu4e-compose.el b/mu4e/mu4e-compose.el
index 077b0e3a..bd1fd602 100644
--- a/mu4e/mu4e-compose.el
+++ b/mu4e/mu4e-compose.el
@@ -825,10 +825,12 @@ draft message."
 (defun mu4e~compose-browse-url-mail (url &optional ignored)
   "Adapter for `browse-url-mailto-function."
   (let* ((headers (rfc2368-parse-mailto-url url))
-	  (to (cdr (assoc "To" headers)))
-	  (subject (cdr (assoc "Subject" headers)))
-	  (body (cdr (assoc "Body" headers))))
-    (mu4e~compose-mail to subject)
+	 (to (cdr (assoc "To" headers)))
+	 (cc (assoc "Cc" headers))
+	 (bcc (assoc "Bcc" headers))
+	 (subject (cdr (assoc "Subject" headers)))
+	 (body (cdr (assoc "Body" headers))))
+    (mu4e~compose-mail to subject (delq nil `(,cc ,bcc)))
     (if body
       (progn
 	(message-goto-body)

Note that Org have also a table of entities (see org-entities) but not complete and
not handy to use out of org context.
The helm table is here
https://github.com/emacs-helm/helm/blob/master/helm-utils.el#L97


> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by djcb** [comment]
Hmm, this is an internal mu4e function, what's the use-case for this?

**Comment by thierryvolpiatto** [comment]
Dirk-Jan C. Binnema <notifications@github.com> writes:

> Hmm, this is an internal mu4e function, what's the use-case for this?

Dunno, I don't use this personally.

-- 
Thierry

**Comment by amosbird** [comment]
Um, I use `mu4e` as a `x-scheme-handler/mailto`. I'm not sure if this function is the right choice, but this works fine,
```
    (defun ab-url-mail (url)
      ""
      (interactive)
      (mu4e~compose-browse-url-mail url))
```

and  ` emacsclient -s mail -eval "(ab-url-mail \"$url\")"`

**Comment by thierryvolpiatto** [comment]
Amos Bird <notifications@github.com> writes:

> I'm not sure if this function is the right choice,

Perhaps you have better time using `find-file-at-point` ?

--
Thierry

**Comment by djcb** [comment]
I'd recommend against using internal (`mu4e~`) function/variables, they are not stable. Of course, feature-requests are welcome but please always include your use-case, as well as emacs/mu4e versions, thanks.

**Comment by djcb** [comment]
So, the easiest solution is to simply remove `mu4e~compose-browse-url-mail` and let emacs' generic facilities (`browse-url`) deal with this.

@amosbird: in your script, simply use `browse-url` instead of `mu4e~compose-browse-url-mail`, and make sure you set the `mail-user-agent`, i.e. 
```
(setq mail-user-agent 'mu4e-user-agent)
```
This handles the Cc: as well, but not the `&amp;`, as @thierryvolpiatto mentioned; I think that is actually the correct behavior; since we're passing normal URIs here, so the `&` should be `&`, not `&amp;'.

**Comment by amosbird** [comment]
@djcb well I just configured mu4e as what you said. But the Cc: is still not handled.
