### ISSUE TITLE
mu4e-view-use-gnus: some messages have character decoding problems

### ISSUE THREAD

**Issue by ardpp** [djcb/mu#1262]
## Expected or desired behavior

In a message with subject äüÜßö and the same message content both should look the same with any setting of `mu4e-view-use-gnus`. (They do so with the now default setting of that variable which is nil.)

## Actual behavior

With `mu4e-view-use-gnus` set to t. The subject looks as it should äüÜßö, but the message content is \344\374\334\337\366

This is similar to https://github.com/djcb/mu/issues/1260 where the same used to happen to subject. Are there some additional settings that I am missing?

**Comment by djcb** [comment]
Please attach the raw message where this occurred (censored as needed)

**Comment by ardpp** [comment]
The raw message is attached. Hopefully censored enough.
[raw.txt](https://github.com/djcb/mu/files/2099888/raw.txt)

**Comment by djcb** [comment]
The problem is not at all related to the subject line and affects _some_ message bodies with non-ascii. Haven't figured out yet exactly when.

The problem is somewhere near `gnus-display-mime`.

**Comment by ardpp** [comment]
Yes it's only _some_ messages. If I send a message to myself with content Äüß using mu4e then the issue is there. If I send a message with the same content using K9 on my smartphone the issue disappears.

**Comment by Chris00** [comment]
Here is a message that has the problem
```
To: Christophe Troestler <Christophe.Troestler@umons.ac.be>
From: XXX <XXX@umons.ac.be>
Date: Tue, 12 Jun 2018 09:05:26 +0200
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.8.0
Content-Type: text/plain; charset="utf-8"; format=flowed
Content-Transfer-Encoding: 8bit
Content-Language: fr-classic


Pour ma part je n'aurai que de quelques remarques mineures. Je pense 
que, en gros, le rapport est acceptable. Je suppose qu'il ne faut pas 
répondre (avec une critique) sur le rapport pour le 25/6 mais seulement 
demander une correction de fautes si on en voit, non ?
```

**Comment by Chris00** [comment]
The problem for this message is with `format=flowed`.

**Comment by ardpp** [comment]
I can confirm that using the default value of `mu4e-compose-format-flowed` which is `nil` my own messages do not have decoding problems.

**Comment by djcb** [comment]
I committed a minimal version of this, which seems to fix the problem for the test message here (though there are still some problem cases with other messages) -- so thanks for your work on this. 

Does this indeed fix things for you?

**Comment by Chris00** [comment]
It is better but it does not always work.  Here is a message that is not correctly decoded.
```
From: Christophe <Christophe@be>
To: Hadrien <Hadrien@be>
Date: Mon, 3 Sep 2018 11:16:49 +0200
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

Dép.
```

**Comment by Chris00** [comment]
UTF-8 messages in the draft folder are not properly decoded — they do not have a `Content-type`, so, as I understand it, the coding system must be right when the message is loaded into the buffer.

**Comment by Emantor** [comment]
I fixed my charset problems by moving the enable mutlibyte after the article-de-quoted-unreadable i.e.
```
      gnus-summary-buffer (get-buffer-create " *appease-gnus*")
      gnus-original-article-buffer (current-buffer))
        (article-de-base64-unreadable)
        (article-de-quoted-unreadable)
        (mm-enable-multibyte)
```

**Comment by Emantor** [comment]
Is there a reason why
```
(article-de-base64-unreadable)
(article-de-quoted-unreadable)
```
are called explictly? The following:
```
  diff --git a/mu4e/mu4e-view.el b/mu4e/mu4e-view.el
  index a1af902c..2a7d1e7c 100644
  --- a/mu4e/mu4e-view.el
  +++ b/mu4e/mu4e-view.el
  @@ -372,13 +372,11 @@ article-mode."
      gnus-summary-buffer (get-buffer-create " *appease-gnus*")
      gnus-original-article-buffer (current-buffer))
         (mm-enable-multibyte)
  -      (article-de-base64-unreadable)
  -      (article-de-quoted-unreadable)
  +      (run-hooks 'gnus-article-decode-hook)
  +      (setq gnus-article-decoded-p gnus-article-decode-hook)
         (gnus-article-prepare-display)
         (mu4e-view-mode)
         (setq mu4e~view-msg msg)
  -      (run-hooks 'gnus-article-decode-hook)
  -      (setq gnus-article-decoded-p gnus-article-decode-hook)
         (set-buffer-modified-p nil)
         (read-only-mode))))
```
Fixes my decoding Issues (and calls `run-hooks` and gnus-article-prepare-display` in the same order as `mm-view` in emacs)

**Comment by jackrandom** [comment]
I still have these problems. Is there any update how this can be fixed?
![screenshot from 2019-01-30 23-03-47](https://user-images.githubusercontent.com/5002075/52015937-7922a300-24e3-11e9-8e3e-c0e036bafb1b.png)


[raw_msg.txt](https://github.com/djcb/mu/files/2814686/raw_msg.txt)

**Comment by djcb** [comment]
Okay, I think all known decoding problems have been fixed (with @Chris00's help), Closing
