### ISSUE TITLE
 mu4e shows attachment instead of message text

### ISSUE THREAD

**Issue by haji-ali** [djcb/mu#1379]
I received an email with a text attachment, and for some reason, the text from the attachment shows up when I view the message in `mu4e` instead of the message text, even though the text shows up correctly in other mail clients.

This is an example message (stripped of personal details)

```
From: Sender
To: Me
Subject: Subject
Thread-Topic: Topic
Date: Thu, 14 Feb 2019 14:29:46 +0000
Content-Type: multipart/mixed;
	boundary="_004_CWXP265MB136590B45CB65FB87E2F88EDA9670CWXP265MB1365GBRP_"
MIME-Version: 1.0

--_004_CWXP265MB136590B45CB65FB87E2F88EDA9670CWXP265MB1365GBRP_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
1">
<style type=3D"text/css" style=3D"display:none;"><!-- P {margin-top:0;margi=
n-bottom:0;} --></style>
</head>
<body dir=3D"ltr">
This is a test
</body>
</html>

--_004_CWXP265MB136590B45CB65FB87E2F88EDA9670CWXP265MB1365GBRP_
Content-Type: text/plain; name="amounts.txt"
Content-Description: amounts.txt
Content-Disposition: attachment; filename="amounts.txt"; size=474;
	creation-date="Wed, 16 Jan 2019 13:52:51 GMT";
	modification-date="Wed, 16 Jan 2019 13:52:51 GMT"
Content-Transfer-Encoding: base64

YW1vdW50DQo0NTcuNTUNCjc1LjAwDQoxOC4wMA0KNTAuMDANCjE4OS4wMA0KMjUuMDANCjI1LjAw
DQo5Ny4yMA0KNDAuMDANCjMwLjAwDQo1MC4wMA0KMzYuOTUNCjEwMC4wMA0KMzAwLjAwDQozMTYu
OTQNCjQ5LjAwDQo4LjUwDQoxMC4wMA0KODUuMDMNCjE1Ni40MQ0KNTAuMDANCjE1Ljk5DQo1OS4w
MA0KOS45OQ0KMjgxLjk1DQoxNS4wMA0KMTAwLjAwDQo4NC43Mw0KMTUwLjAwDQoxNDguMzkNCjQ1
LjU4DQoyOC45NA0KMTIwLjAwDQo4OC4wMA0KMTEwLjAwDQo2NS4wMA0KNTguNDkNCjUwMy4wMA0K
MTAuMDANCjc1NS4wMA==
```

If I copy this email to a message folder and view it with mu4e, the text inside `amounts.txt` shows up instead of the text `"This is a test"`.

Note: If I press `h` or call `mu4e-view-toggle-html` the text switches back and forth between the attachment and the message text. It seems that `mu4e` is ignoring the fact that `amount.txt` is an attachment.

**Comment by haji-ali** [comment]
After some more googling, I found the same issue here #1072.

Are there any other workarounds besides using gnus? I got used to mu4e default view and I like being able to view my messages in plain text (plus I have no idea how to open links in html view using the keyboard).

**Comment by djcb** [comment]
This is resolved now; see #1380.

**Comment by haji-ali** [comment]
Is this on master? I just pulled the latest changes and the message I included still shows the text attachment by default in mu4e default message view.

**Comment by djcb** [comment]
This is what it shows right now:
```
From: Sender
To: Me
Subject: Subject
Number of recipients: 1
Flags: seen, attach
Date: 2019-02-14 16:29
Maildir: /inbox
Message-Id: ca4a596fffe1cd6a@fake-msgid
Attachments: [1]amounts.txt(406)

This is a test 
```

but it won't automatically apply to _old_ messages ; so you might need a rebuild. Also, you need to rebuild mu/mu4e and restart it and ensure you use this updated version. Sorry if that sounds obvious, but sometimes people forget it.

**Comment by haji-ali** [comment]
Oh sorry. It was not obvious to me at all that mu needs rebuilding (I only rebuilt mu4e). Thanks for explaining.
