### ISSUE TITLE
mu4e-headers-toogle-include-related does not work anymore

### ISSUE THREAD

**Issue by nils-schween** [djcb/mu#1911]
Hi everyone,

I just pulled the latest changes and unfortunately `mu4e-headers-toogle-include-related` does not work anymore.
I expected it to also include my answers in the threads. Typing `W` does not change anything. It "reloads" the headers, but the shown emails are they same. Probably you can reproduce this behaviour by pulling the latest changes and typing `W` in the header view.
Are you experiencing the same?
Thank you,
Nils

**Comment by djcb** [comment]
It works for me, e.g.
```
lib/index % mu find hello | wc -l
5187
lib/index % mu find hello --include-related | wc -l
9396
```
so some more detail is needed. Does running regenerating the database help?

**Comment by nils-schween** [comment]
Thanks for your quick reply.
Hmm ... that's strange. If I execute the same commands, I also do get different numbers. And second one is higher. Nonetheless, in header view in a thread, I do not see any emails I sent. I checked the `*Messages*`buffer and I do get the following error:
`
error in process sentinel: mu4e-alert--parse-mails: Invalid read syntax: ") or . in a vector"
error in process sentinel: Invalid read syntax: ") or . in a vector"
`
Deactivating mu4e-alert makes the error message disappear. But still, the threads do not include my own mails. Hmm ..

**Comment by djcb** [comment]
The latter seems like a problem with mu4e-alert I guess... 

Anyway, can you try to re-generate the database, i.e., with `mu init`?

**Comment by nils-schween** [comment]
Oh ... I directly edited my post, since I had forgotten to say, that I did re-generate the database. Probably you haven't seen the updated post. Unfortunately, it did not help. Still no email, which I had sent, in my threads.

**Comment by djcb** [comment]
And... how many messages are in your inbox? Does it make a difference when you press `Q` (for a full-search rather than only 500)?

If that doesn't make a difference, it's best trying to reproduce with command-line searches, something like
```
mu find maildir:/inbox --include-related 
```
(change "/inbox" as needed).

**Comment by nils-schween** [comment]
I just checked it, it does make a difference. If I toggle a full-search with `Q`, I can see my messages again.	
Here a rough list of my mailboxes and their respective size:
```
/maildir1/INBOX              (0/864)
/maildir1/otherFolder1     (0/126)
/maildir1/otherFolder2     (0/406)
/maildir1/otherfolder3      (0/56)
/maildir1/otherfolder4      (0/446)
/maildir2/INBOX                   (0/2785)
/maildir2/manyotherFolder (0/~5500)
maildir2/archiveFolde (0/~6000)
maildir3/INBOX                   (0/~500)
```
Command line searches work without any problem for all mailboxes. 
Thank you once more

**Comment by stsquad** [comment]
If you enable mu daemon debugging (mu4e-mu-debug t) and follow the logs (journalctl -f _COMM=mu) do you see lots of:

   can't find document 3270413

when searching. Because currently my searching is broken although it looks very much like not including related I think it's a deeper problem with the daemon finding things.

**Comment by nils-schween** [comment]
Hi Alex,
thanks for getting involved.
You were right. Here is my journal output:
```
Jan 24 20:02:40 laptop mu[17293]: can't find document 1893
Jan 24 20:02:40 laptop mu[17293]: can't find document 1894
Jan 24 20:02:40 laptop mu[17293]: can't find document 1896
Jan 24 20:02:40 laptop mu[17293]: can't find document 1897
Jan 24 20:02:40 laptop mu[17293]: can't find document 1898
Jan 24 20:02:40 laptop mu[17293]: can't find document 2225
Jan 24 20:02:40 laptop mu[17293]: can't find document 2501
Jan 24 20:02:40 laptop mu[17293]: can't find document 2735
Jan 24 20:02:40 laptop mu[17293]: can't find document 3035
```

**Comment by stsquad** [comment]
Hmm curious. So running:

    /mu/mu find "(from:alex.bennee OR from:bennee.com)" -r -d

On the command line seems to show related threads, however with -t it causes a crash:

    ./mu/mu find "(from:alex.bennee OR from:bennee.com)" -r -d -t
    mu: mu-query-threads.cc:74: void Container::remove_child(Container&): Assertion `has_child(child)' failed.
    fish: “./mu/mu find "(from:alex.bennee…” terminated by signal SIGABRT (Abort)

When I turn threading off in the mu4e I see some of the missing messages but obviously not threaded. I wonder if that explains some of what is going on?

**Comment by stsquad** [comment]
For reference the backtrace on the command line:

    Program received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff70fb7bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff70e6535 in __GI_abort () at abort.c:79
    #2  0x00007ffff70e640f in __assert_fail_base (fmt=0x7ffff7248ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555555d2d29 "has_child(child)", file=0x5555555d2d14 "mu-query-threads.cc", line=74, function=<optimized out>) at assert.c:92
    #3  0x00007ffff70f4102 in __GI___assert_fail (assertion=assertion@entry=0x5555555d2d29 "has_child(child)", file=file@entry=0x5555555d2d14 "mu-query-threads.cc", line=line@entry=74, function=function@entry=0x5555555d2f40 <Container::remove_child(Container&)::__PRETTY_FUNCTION__> "void Container::remove_child(Container&)") at assert.c:101
    #4  0x00005555555922b3 in Container::remove_child(Container&) (child=..., this=<optimized out>) at mu-query-threads.cc:93
    #5  0x00005555555922b3 in prune_empty_containers(Container&) (container=...) at mu-query-threads.cc:296
    #6  0x0000555555592064 in <lambda(auto:2&&)>::operator()<Container* const&> (__closure=<optimized out>, child=@0x55555a81a820: 0x55555a81ca78) at mu-query-threads.cc:287
    #7  0x0000555555592064 in Container::for_each_child<prune_empty_containers(Container&)::<lambda(auto:2&&)> > (func=..., this=0x55555c458888) at mu-query-threads.cc:105
    #8  0x0000555555592064 in prune_empty_containers(Container&) (container=...) at mu-query-threads.cc:287
    #9  0x0000555555592f39 in prune_empty_containers (id_table=Python Exception <class 'IndexError'> list index out of range:
    std::unordered_map with 98088 elements) at mu-query-threads.cc:325
    #10 0x0000555555592f39 in calculate_threads_real<Mu::QueryResults> (descending=<optimized out>, sort_field=<optimized out>, qres=...) at mu-query-threads.cc:492
    #11 0x0000555555592f39 in Mu::calculate_threads(Mu::QueryResults&, unsigned char, bool) (qres=..., sort_field=16 '\020', descending=descending@entry=false) at mu-query-threads.cc:511
    #12 0x000055555558dbc3 in Mu::Query::Private::run_threaded(Mu::QueryResults&, Xapian::Enquire&, unsigned char, Mu::QueryFlags, unsigned long) const (this=<optimized out>, qres=..., enq=..., sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=4354923) at mu-query.cc:144
    #13 0x000055555558e382 in Mu::Query::Private::run_related(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=0x55555735d5e0, expr=..., sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=4354923) at mu-query.cc:198
    #14 0x000055555558e3f1 in Mu::Query::Private::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=<optimized out>, expr="(from:alex.bennee OR from:bennee.com)", sortfieldid=sortfieldid@entry=16 '\020', qflags=qflags@entry=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=maxnum@entry=0) at mu-query.cc:208
    #15 0x000055555558e53a in Mu::Query::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=this@entry=0x7fffffffde30, expr="(from:alex.bennee OR from:bennee.com)", sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=0) at /usr/include/c++/8/bits/unique_ptr.h:342
    #16 0x0000555555573b50 in run_query (err=0x7fffffffe258, opts=0x7fffffffdfc0, expr="(from:alex.bennee OR from:bennee.com)", q=...) at mu-cmd-find.cc:110
    #17 0x0000555555573b50 in process_query (err=0x7fffffffe258, opts=0x7fffffffdfc0, expr="(from:alex.bennee OR from:bennee.com)", q=...) at mu-cmd-find.cc:615
    #18 0x0000555555573b50 in execute_find (err=0x7fffffffe258, opts=0x7fffffffdfc0, store=...) at mu-cmd-find.cc:642
    #19 0x0000555555573b50 in Mu::mu_cmd_find(Mu::Store const&, Mu::_MuConfig const*, _GError**) (store=..., opts=opts@entry=0x5555555f2c60 <MU_CONFIG>, err=err@entry=0x7fffffffe258) at mu-cmd-find.cc:723
    #20 0x0000555555577aac in cmd_find (err=0x7fffffffe258, opts=0x5555555f2c60 <MU_CONFIG>) at mu-cmd.cc:644
    #21 0x0000555555577aac in Mu::mu_cmd_execute(Mu::_MuConfig const*, _GError**) (opts=opts@entry=0x5555555f2c60 <MU_CONFIG>, err=err@entry=0x7fffffffe258) at mu-cmd.cc:717
    #22 0x000055555556f181 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at mu.cc:130

**Comment by stsquad** [comment]
I did some bisecting but a bunch of the commits are broken for me:

# only skipped commits left to test
# possible first bad commit: [035a10ab49439bd1d2e250d87d369307d86a31b3] remove obsolete threading tests
# possible first bad commit: [68a75c2c91f74e50881ac706f1ad60f0928c3428] mu4e: make thread indicators a bit lighter
# possible first bad commit: [98744c66f75ac6d1942ff9af52b1a38b4bcbc7ec] remove some dead code
# possible first bad commit: [362c53a7e7c4aa3af37eb333fddfb800aecd5369] mu4e: headers: fix some compiler warnings
# possible first bad commit: [36684c9e976622c581c865ffa3c7b58cef890ea6] mu: use sha-1 for fallback msgid
# possible first bad commit: [af386824f24075c88a02f38bc188dc46fb950fd1] contacts: remove some dead code
# possible first bad commit: [fb34824232588e4544f9a7b946e94d28d7ce6de3] contacts: only sort recent contacts by recency
# possible first bad commit: [9a1e749cc5321064595bbaa0ce5e2da02ac2049a] threads: update unit tests
# possible first bad commit: [90e35a9732e19dfa0ebd78655d014a9d624d29eb] toys/mug: upgrade for query changes
# possible first bad commit: [4daa7105d26bb57b2c0ee3dde0622f358f4c955e] guile: update for query changes
# possible first bad commit: [01ced9a356704bf7cd68d07ecdac20ab6717557d] mu: Update for new querying APIs
# possible first bad commit: [e282d80bc0ef3630984871e5f7b4a0c707234eff] lib: Update for new querying machinery
# possible first bad commit: [95dffb98a637c54129404cb50edd67b456fa4f43] query: Rework querying/threading machinery

However commit 86e1515c71ca628456e3f1957f69c60433f1bd6c works for me.

**Comment by nils-schween** [comment]
Thanks! I did the same. I reseted my repository to 86e1515. Now, it works again.

**Comment by djcb** [comment]
I guess some different issues...

First one, some related messages are not visible when the search-maxnum of messages is limited: the algo has to choose which messages to show and which not... I have a small update (in git) so it'll favor the related messages (when showing threads). Does that help?

Second, the assert is some internal prob in the new algo... I'll investigate. I can imagine bisecting wouldn't quite work, the patchset can best be treated as a unit.

**Comment by stsquad** [comment]
Hmm I'll have to test later when I can restart emacs - the crash certainly still occurs with the current state of master as of just now. Do you want me to raise a new bug for that?

**Comment by stsquad** [comment]
Hmm with the latest head via mu4e I'm still failing:

    error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6
    error in process sentinel: mu server process received signal 6
    error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6
    error in process sentinel: mu server process received signal 6
    
which I guess means it's still crashing somewhere?

**Comment by stsquad** [comment]
Hmm a full clean rebuild made this go away. I'd really like to get to the bottom of what is being left over that keeps tripping up the build.

**Comment by djcb** [comment]
I've pushed another change that should avoid the assert-failure... the signal-6 (SIGABRT, which is consistent with an assert-failure) might be that same issue. There must be something specific in your mail corpus that triggers this; but while we're testing, no need to abort().

**Comment by stsquad** [comment]
This doesn't fix it for me, has_child doesn't seem to stop it asserting bellow:

```
Starting program: /home/alex/src/emacs/mu/mu.git/mu/mu find \(from:alex.bennee\ OR\ from:bennee.com\) -r -d -t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
mu: mu-query-threads.cc:74: void Container::remove_child(Container&): Assertion `has_child(child)' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff70fb7bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff70e6535 in __GI_abort () at abort.c:79
#2  0x00007ffff70e640f in __assert_fail_base (fmt=0x7ffff7248ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555555d2d29 "has_child(child)", file=0x5555555d2d14 "mu-query-threads.cc", line=74, function=<optimized out>) at assert.c:92
#3  0x00007ffff70f4102 in __GI___assert_fail (assertion=assertion@entry=0x5555555d2d29 "has_child(child)", file=file@entry=0x5555555d2d14 "mu-query-threads.cc", line=line@entry=74, function=function@entry=0x5555555d2f60 <Container::remove_child(Container&)::__PRETTY_FUNCTION__> "void Container::remove_child(Container&)") at assert.c:101
#4  0x0000555555592347 in Container::remove_child(Container&) (child=..., this=<optimized out>) at mu-query-threads.cc:298
#5  0x0000555555592347 in prune_empty_containers (container=...) at mu-query-threads.cc:300
#6  0x0000555555592347 in prune_empty_containers(Container&) (container=...) at mu-query-threads.cc:285
#7  0x0000555555592094 in <lambda(auto:2&&)>::operator()<Container* const&> (__closure=<optimized out>, child=@0x555558f4e6c0: 0x555558f4f0b8) at mu-query-threads.cc:287
#8  0x0000555555592094 in Container::for_each_child<prune_empty_containers(Container&)::<lambda(auto:2&&)> > (func=..., this=0x55555a88f388) at mu-query-threads.cc:105
#9  0x0000555555592094 in prune_empty_containers(Container&) (container=...) at mu-query-threads.cc:287
#10 0x0000555555592094 in <lambda(auto:2&&)>::operator()<Container* const&> (__closure=<optimized out>, child=@0x55555a88edc0: 0x55555a88f388) at mu-query-threads.cc:287
#11 0x0000555555592094 in Container::for_each_child<prune_empty_containers(Container&)::<lambda(auto:2&&)> > (func=..., this=0x55555a88f308) at mu-query-threads.cc:105
#12 0x0000555555592094 in prune_empty_containers(Container&) (container=...) at mu-query-threads.cc:287
#13 0x0000555555592fb9 in prune_empty_containers (id_table=Python Exception <class 'IndexError'> list index out of range:
std::unordered_map with 98143 elements) at mu-query-threads.cc:330
#14 0x0000555555592fb9 in calculate_threads_real<Mu::QueryResults> (descending=<optimized out>, sort_field=<optimized out>, qres=...) at mu-query-threads.cc:497
#15 0x0000555555592fb9 in Mu::calculate_threads(Mu::QueryResults&, unsigned char, bool) (qres=..., sort_field=16 '\020', descending=descending@entry=false) at mu-query-threads.cc:516
#16 0x000055555558dbc3 in Mu::Query::Private::run_threaded(Mu::QueryResults&, Xapian::Enquire&, unsigned char, Mu::QueryFlags, unsigned long) const (this=<optimized out>, qres=..., enq=..., sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=4356062) at mu-query.cc:144
#17 0x000055555558e3b2 in Mu::Query::Private::run_related(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=0x55555735e2a0, expr=..., sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=4356062) at mu-query.cc:200
#18 0x000055555558e421 in Mu::Query::Private::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=<optimized out>, expr="(from:alex.bennee OR from:bennee.com)", sortfieldid=sortfieldid@entry=16 '\020', qflags=qflags@entry=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=maxnum@entry=0) at mu-query.cc:210
#19 0x000055555558e56a in Mu::Query::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char, Mu::QueryFlags, unsigned long) const (this=this@entry=0x7fffffffe150, expr="(from:alex.bennee OR from:bennee.com)", sortfieldid=<optimized out>, qflags=(Mu::QueryFlags::IncludeRelated | Mu::QueryFlags::Threading), maxnum=0) at /usr/include/c++/8/bits/unique_ptr.h:342
#20 0x0000555555573b50 in run_query (err=0x7fffffffe578, opts=0x7fffffffe2e0, expr="(from:alex.bennee OR from:bennee.com)", q=...) at mu-cmd-find.cc:110
#21 0x0000555555573b50 in process_query (err=0x7fffffffe578, opts=0x7fffffffe2e0, expr="(from:alex.bennee OR from:bennee.com)", q=...) at mu-cmd-find.cc:613
#22 0x0000555555573b50 in execute_find (err=0x7fffffffe578, opts=0x7fffffffe2e0, store=...) at mu-cmd-find.cc:640
#23 0x0000555555573b50 in Mu::mu_cmd_find(Mu::Store const&, Mu::_MuConfig const*, _GError**) (store=..., opts=opts@entry=0x5555555f2c60 <MU_CONFIG>, err=err@entry=0x7fffffffe578) at mu-cmd-find.cc:721
#24 0x0000555555577aac in cmd_find (err=0x7fffffffe578, opts=0x5555555f2c60 <MU_CON

```

**Comment by stsquad** [comment]
Not sure this is helpful but this is the result of my rr session:

[gdb.txt](https://github.com/djcb/mu/files/5868438/gdb.txt)

**Comment by nils-schween** [comment]
@djcb Thanks for your effort. I just pulled your changes and recompiled mu and I also rebuilt the database. Now I also get the following error message in one of mailboxes:
`error in process sentinel: mu4e~proc-sentinel: mu server process received signal 6
error in process sentinel: mu server process received signal 6
`
For the other mail boxes, header view opens and some of threads contain the messages I sent, but not all threads. Hmmm ... this seems to be quite tricky.

**Comment by djcb** [comment]
Well, I'll have to do some more investigation. I've turned off the offending assert for now. Thanks for the debug logs, those while be helpful.

As for thread contents, if the number messages + related messages > 500, then some messages will not be shown... ideally we'd prefer to show full threads.

**Comment by nils-schween** [comment]
> As for thread contents, if the number messages + related messages > 500, then some messages will not be shown... ideally we'd prefer to show full threads.

Hmm ... I am wondering about the counting. Depending on if threading is activated or not, the units could be threads instead of emails. And then the limit would be 500 threads ( or 300) rather than 500 emails. But that's probably hard to implement.

**Comment by stsquad** [comment]
Where is cN->query_match set? I'm seeing it as null for one or other while doing sort_sibblings:

    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015e5a50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:0x6100015dbd50/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:0x6100015dbd50
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:43 zen mu[10722]: missing query_match c1:(nil)/c2:(nil)
    Jan 31 21:31:44 zen mu[10722]: query '(from:alex.bennee OR from:bennee.com)'; related: yes; threads: yes; max-size: 0: finished after 5.0 s

**Comment by nils-schween** [comment]
@djcb thanks! it seems to work again - that's really great.
