### ISSUE TITLE
Missing rest of thread context when searching for (from:self)

### ISSUE THREAD

**Issue by stsquad** [djcb/mu#1924]
## Expected or desired behavior

When I search for threads I'm participating in with:

    (recip:alex.bennee OR recip:bennee.com)
  
I expect the rest of the thread to show up.
  
## Actual behaviour

Please describe the behavior you are actually seeing.

I get a mixed picture. For some threads it seems to show up but for some others I just get the email I sent. The email has a proper In-reply-to header and if I search for that id I get the whole thread in question.

This appears to be a result of the recent threading changes.

## Versions of mu, mu4e/emacs, operating system etc.

Current mu git HEAD, emacs native-comp branch, Linux Debian 10

**Comment by stsquad** [comment]
I think `flag:unread` behaviour has also changed. Before it would still display the rest of the thread if any of the thread was unread. This made it easy to work through threads by doing:

    (list:qemu-devel* OR recip:qemu-devel@nongnu.org) and flag:unread
    
and then marking whole threads as read as I worked through them. Now I just see the unread articles which doesn't include the context of discussions that have been had but previously read.

**Comment by djcb** [comment]
There have been some updates in the threading... can you try again?

**Comment by stsquad** [comment]
I messed up the original comment. The normal search I use is:

    (from:alex.bennee OR from:bennee.com)

which in the log generates:

    query '(from:alex.bennee OR from:bennee.com)'; related: yes; threads: yes; max-size: 1000: finished after 1031.2 ms

but on my display results in only messages from me, for example un-threaded replies as well as threads I started:

    �4422407�  09:08:18     ✔                 Alex Bennée            Re: [PATCH v3 0/5] Move remaining x86 Travis jobs to the gitlab-CI
    �4422405�  08:58:12     ✔                 Alex Bennée            Re: [PATCH] virtio: disable ioeventfd for record/replay
    �4421682�  Wed 10/02/21 ✱⎕                Alex Bennée            [PATCH  v2 00/21] plugins/next pre-PR (hwprofile, regression fixes, icount count fix)
    �4421674�  Wed 10/02/21 ✱⎕                Alex Bennée            │ [PATCH  v2 01/21] hw/virtio/pci: include vdev name in registered PCI sections
    �4421680�  Wed 10/02/21 ✱⎕                Alex Bennée            │ [PATCH  v2 02/21] plugins: add API to return a name for a IO device
    �4421684�  Wed 10/02/21 ✱⎕                Alex Bennée            │ [PATCH  v2 03/21] plugins: new hwprofile plugin
    �4421675�
    ....

although weirdly if I scroll down there are some threads from 2017 that include other people. When I switch to:

    recip:alex.bennee flag:unread
  
I do see replies from other people but obviously not threads where I was the tail comment. Also read entries are missing so threads start without the previous context.

Tested with 936fd3f4.

**Comment by djcb** [comment]
When I try:
```
mu find '(from:alex.bennee OR from:bennee.com)' --skip-dups --include-related --threads -n 1000
```
I can see threads with you and others in it (54 results for the above). I bet you have more messages with you in it :)

Probably superfluous, did you do an `./autogen.sh` before rebuilding? I've some cases where that makes a difference.

**Comment by stsquad** [comment]
How old are those threads? There seems to be some sort of time related thing because recent threads are missing the related stuff by historical aren't. As this slightly hacky one liner demonstrates:

    $ ./mu/mu find '(from:alex.bennee OR from:bennee.com)' --skip-dups --include-related --threads -n 100  --sortfield=date --reverse --fields "f" |   cut -d ">" -f 2 | sort | uniq | wc -l
    2

2 because there is a blank line

    $ ./mu/mu find '(from:alex.bennee OR from:bennee.com)' --skip-dups --include-related --threads -n 100 --fields "f" |   cut
     -d ">" -f 2 | sort | uniq | wc -l
    22

More concretely a sample of the view of a thread with the from search:

      Tue 09/02/21 ✔                 Alex Bennée            │ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4422513�  10:28:07     ✔                 Alex Bennée            │ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4421682�
    
but when I switch to using the parent thread to search (i:622e8281-eeda-2620-d388-69d9d6853788@amsat.org):

    �4409480�  Sun 07/02/21 ❮✔                Philippe Mathieu-Daudé [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417543�  Tue 09/02/21 ✔                 Wainer dos Santos Mosc │ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417736�  Tue 09/02/21 ✔                 Philippe Mathieu-Daudé │ └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417741�  Tue 09/02/21 ✔                 Peter Maydell          │   └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417808�  Tue 09/02/21 ❮✔                Philippe Mathieu-Daudé │     └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417840�  Tue 09/02/21 ✔                 Daniel P. Berrangé     │       │ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417814�  Tue 09/02/21 ✔                 Thomas Huth            │       │ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4417838�  Tue 09/02/21 ✔                 Daniel P. Berrangé     │       │ └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4418437�  Tue 09/02/21 ✔                 Alex Bennée            │       └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container
    �4422513�  10:28:07     ✔                 Alex Bennée            └ Re: [PATCH v3] travis-ci: Disable C++ optional objects on AArch64 container

**Comment by djcb** [comment]
I suspect somehow you may have gotten _older_ related messages... `master` has some updates, but I'm not sure we have gotten quite to the bottom of this.

**Comment by stsquad** [comment]
@djcb can you point me to where the "related" searches are kicked off in the code? To my mind after you've fetched the initial set you need to then fetch all emails which either have references to or a referred to by the first set. You then need to exhaust this tree until you've found all the relevant links.

**Comment by djcb** [comment]
in  `mu-query.cc`. We get the thread-ids (root of the referred message-ids) from the first ("leader") query, and then run a second query which is the union of the first query + thread-ids. This hasn't changed.

Do you get all your results when you run an unlimited query (without -n)?

**Comment by stsquad** [comment]
Yes if I drop the -n I get everything. Is this a cull of results to meet the limiting field? This email archive goes back 7 years and many many threads because I'm involved in quite a lot of projects.

**Comment by stsquad** [comment]
OK so I think I know whats happening. When the related threads are filled in it goes in the opposite order to the date sorting, so older related threads are included before newer ones. If I select unlimited results I get everything (although that's 56k lines of mail) but I can approximate my normal view by appending a date range to bring the total hits within grasp. So for example:

    date:2w..now AND (from:alex.bennee OR from:bennee.com)

does show me other peoples replies in my recent threads although I guess I I won't see their replies if my message was older than the date limit.

**Comment by djcb** [comment]
Ah, that's useful. Yeah, that's what I suspected... some unwanted messages are included which fill up the limit, rather than the ones we want. I have pushed some changes for this... does that improve things?

**Comment by stsquad** [comment]
It's certainly improved some threads where I can see the rest of the context but I'm still seeing some that are a series of Re:'s by me but without the parent (and by extension everything else). Prepending date:4w..now AND still works fine though.

**Comment by stsquad** [comment]
I should note I'm seeing a lot of "not found! nnnnnnnn" messages. That are the numbers it's exposing?

**Comment by djcb** [comment]
Yeah, the latter is a debugging leftover, I've removed that now.

**Comment by stsquad** [comment]
Another follow-up question. Where is MU_MSG_FIELD_ID_THREAD_ID derived from? Can I query it from the mu4e interface?

I'm wondering if there might be something going on with de-deplication and messages having different thread ids (e.g. same message in my upstream list folder as well as my mythreads folder as well as my inbox because I was CCed).

**Comment by stsquad** [comment]
I don't know if this is helpful but I did attempt to dump some of the threading information, first a subset of my (from alex.bennee) search without date limiting:

    �4438302�  10:14:49     ✱⎕                Alex Bennée            [PATCH  v2 0/6] testing/next (meson check-tcg, fedora bump, docs)
    �4438300�  10:14:50     ✱⎕                Alex Bennée            │ [PATCH  v2 1/6] meson.build: expose TCG cross compiler information in summary
    �4438296�  10:14:51     ✱⎕                Alex Bennée            │ [PATCH  v2 2/6] docker: Bump Fedora images to release 33
    �4438299�  10:14:52     ✱⎕                Alex Bennée            │ [PATCH  v2 3/6] tests/acceptance: allow a "graceful" failing for virtio-gpu test
    �4438301�  10:14:53     ✱⎕                Alex Bennée            │ [PATCH  v2 4/6] docs/devel: expand on use of containers to build tests
    �4438298�  10:14:55     ✱⎕                Alex Bennée            │ [PATCH  v2 6/6] docs/devel: add forward reference to check-tcg
    �4438297�  10:14:54     ✱⎕                Alex Bennée            └ [PATCH  v2 5/6] docs/devel: update the container based tests
    �4438470�  12:14:33     ✔                 Alex Bennée              └ Re: [PATCH v2 5/6] docs/devel: update the container based tests

    ((((thread :path "12a7:fffa:ffff:z" :level 2 :date "" :related t :first-child t :last-child t)
      (docid . 4438470)
      (subject . "Re: [PATCH v2 5/6] docs/devel: update the container based tests")
      (maildir . "/sent")
      (msgid . "874ki470zp.fsf@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-6-alex.bennee@linaro.org" "a28b2c23-418b-83f7-c045-e82a11b95ae3@redhat.com"))
     ((thread :path "12a7:fffa:z" :level 1 :date "" :related t :last-child t :has-child t)
      (docid . 4438297)
      (subject . "[PATCH  v2 5/6] docs/devel: update the container based tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-6-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:fffb:z" :level 1 :date "" :related t)
      (docid . 4438298)
      (subject . "[PATCH  v2 6/6] docs/devel: add forward reference to check-tcg")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-7-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:fffc:z" :level 1 :date "" :related t)
      (docid . 4438301)
      (subject . "[PATCH  v2 4/6] docs/devel: expand on use of containers to build tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-5-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:fffd:z" :level 1 :date "" :related t)
      (docid . 4438299)
      (subject . "[PATCH  v2 3/6] tests/acceptance: allow a \"graceful\" failing for virtio-gpu test")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-4-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:fffe:z" :level 1 :date "" :related t)
      (docid . 4438296)
      (subject . "[PATCH  v2 2/6] docker: Bump Fedora images to release 33")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-3-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:ffff:z" :level 1 :date "" :related t :first-child t)
      (docid . 4438300)
      (subject . "[PATCH  v2 1/6] meson.build: expose TCG cross compiler information in summary")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-2-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "12a7:z" :level 0 :date "1613996073" :root t :related t :has-child t :thread_subject t docid subject maildir msgid references)
      (docid . 4438302)
      (subject . "[PATCH  v2 0/6] testing/next (meson check-tcg, fedora bump, docs)")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-1-alex.bennee@linaro.org")
      (references)))

The second is the same search with the date limiting turned on:

    �4438302�✱ 10:14:49     ✱⎕                Alex Bennée            [PATCH  v2 0/6] testing/next (meson check-tcg, fedora bump, docs)
    �4438300�✱ 10:14:50     ✱⎕                Alex Bennée            │ [PATCH  v2 1/6] meson.build: expose TCG cross compiler information in summary
    �4438296�✱ 10:14:51     ✱⎕                Alex Bennée            │ [PATCH  v2 2/6] docker: Bump Fedora images to release 33
    �4438299�✱ 10:14:52     ✱⎕                Alex Bennée            │ [PATCH  v2 3/6] tests/acceptance: allow a "graceful" failing for virtio-gpu test
    �4438301�✱ 10:14:53     ✱⎕                Alex Bennée            │ [PATCH  v2 4/6] docs/devel: expand on use of containers to build tests
    �4438453�✱ 11:39:35     ✔                 Thomas Huth            │ └ Re: [PATCH v2 4/6] docs/devel: expand on use of containers to build tests
    �4438297�✱ 10:14:54     ✱⎕                Alex Bennée            │ [PATCH  v2 5/6] docs/devel: update the container based tests
    �4438452�✱ 11:46:15     ❮✔                Thomas Huth            │ └ Re: [PATCH v2 5/6] docs/devel: update the container based tests
    �4438470�✱ 12:14:33     ✔                 Alex Bennée            │   └ Re: [PATCH v2 5/6] docs/devel: update the container based tests
    �4438485�✱ 12:15:58     ✱⎕                Thomas Huth            │     └ Re: [PATCH v2 5/6] docs/devel: update the container based tests
    �4438298�✱ 10:14:55     ✱⎕                Alex Bennée            └ [PATCH  v2 6/6] docs/devel: add forward reference to check-tcg
    �4438436�✱ 11:36:54     ✔                 Philippe Mathieu-Daudé   │ Re: [PATCH v2 6/6] docs/devel: add forward reference to check-tcg
    �4438488�✱ 12:16:46     ✱⎕                Thomas Huth              └ Re: [PATCH v2 6/6] docs/devel: add forward reference to check-tcg

    (((thread :path "074:ffa:ffe:z" :level 2 :date "" :related t :last-child t)
      (docid . 4438488)
      (subject . "Re: [PATCH v2 6/6] docs/devel: add forward reference to check-tcg")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "fab653a1-37fd-50ac-70bc-90e8397f6102@redhat.com")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-7-alex.bennee@linaro.org"))
     ((thread :path "074:ffa:fff:z" :level 2 :date "" :related t :first-child t)
      (docid . 4438436)
      (subject . "Re: [PATCH v2 6/6] docs/devel: add forward reference to check-tcg")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20afa72c-da47-431a-6230-45cc46c15afb@amsat.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-7-alex.bennee@linaro.org"))
     ((thread :path "074:ffa:z" :level 1 :date "" :last-child t :has-child t)
      (docid . 4438298)
      (subject . "[PATCH  v2 6/6] docs/devel: add forward reference to check-tcg")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-7-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:ffb:fff:fff:fff:z" :level 4 :date "" :related t :first-child t :last-child t)
      (docid . 4438485)
      (subject . "Re: [PATCH v2 5/6] docs/devel: update the container based tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "c542d84c-7add-d899-3708-1a57bee3cb6a@redhat.com")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-6-alex.bennee@linaro.org" "a28b2c23-418b-83f7-c045-e82a11b95ae3@redhat.com" "874ki470zp.fsf@linaro.org"))
     ((thread :path "074:ffb:fff:fff:z" :level 3 :date "" :first-child t :last-child t :has-child t)
      (docid . 4438470)
      (subject . "Re: [PATCH v2 5/6] docs/devel: update the container based tests")
      (maildir . "/sent")
      (msgid . "874ki470zp.fsf@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-6-alex.bennee@linaro.org" "a28b2c23-418b-83f7-c045-e82a11b95ae3@redhat.com"))
     ((thread :path "074:ffb:fff:z" :level 2 :date "" :related t :first-child t :last-child t :has-child t)
      (docid . 4438452)
      (subject . "Re: [PATCH v2 5/6] docs/devel: update the container based tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "a28b2c23-418b-83f7-c045-e82a11b95ae3@redhat.com")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-6-alex.bennee@linaro.org"))
     ((thread :path "074:ffb:z" :level 1 :date "" :has-child t)
      (docid . 4438297)
      (subject . "[PATCH  v2 5/6] docs/devel: update the container based tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-6-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:ffc:fff:z" :level 2 :date "" :related t :first-child t :last-child t)
      (docid . 4438453)
      (subject . "Re: [PATCH v2 4/6] docs/devel: expand on use of containers to build tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "af0dbc9f-890e-36b8-0fcb-e25a6234ffec@redhat.com")
      (references "20210222101455.12640-1-alex.bennee@linaro.org" "20210222101455.12640-5-alex.bennee@linaro.org"))
     ((thread :path "074:ffc:z" :level 1 :date "" :has-child t)
      (docid . 4438301)
      (subject . "[PATCH  v2 4/6] docs/devel: expand on use of containers to build tests")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-5-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:ffd:z" :level 1 :date "")
      (docid . 4438299)
      (subject . "[PATCH  v2 3/6] tests/acceptance: allow a \"graceful\" failing for virtio-gpu test")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-4-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:ffe:z" :level 1 :date "")
      (docid . 4438296)
      (subject . "[PATCH  v2 2/6] docker: Bump Fedora images to release 33")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-3-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:fff:z" :level 1 :date "" :first-child t)
      (docid . 4438300)
      (subject . "[PATCH  v2 1/6] meson.build: expose TCG cross compiler information in summary")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-2-alex.bennee@linaro.org")
      (references "20210222101455.12640-1-alex.bennee@linaro.org"))
     ((thread :path "074:z" :level 0 :date "1613996206" :root t :has-child t :thread_subject t)
      (docid . 4438302)
      (subject . "[PATCH  v2 0/6] testing/next (meson check-tcg, fedora bump, docs)")
      (maildir . "/linaro/virtualization/qemu")
      (msgid . "20210222101455.12640-1-alex.bennee@linaro.org")
      (references)))

AFAICT the one really is a subset of the other (right down to the same /sent email in the sequence, the main patches having been sent via git-send). The references all seem complete but I've gotten lost trying to follow the Xapian code which is referring to thread-ids (hence my earlier question). Are these transient ID's for the search or a static stable reference?

**Comment by djcb** [comment]
Thanks for this... I'll need to analyze this. Oh, thread-ids (in the database) are the message-id of the root-message in a thread, so they are stable.

So since without the `-n` (or with more bounded searches) we get all the messages you expect, it seems we're removing ones we actually would like to keep. That could be some sorting artifact... but I'll go through the code once again.

**Comment by stsquad** [comment]
Hi @djcb,

So over the weekend I had occasion to rebuild the database. I needed to move my Maildir to another partition so I took the opertunity to clean-up my isync setup. I reduced the directory depth by one (originally I had multiple email accounts in my Maildir) and I also deleted the duplicate of [GMail]/All Mail. Obviously this needed a complete re-index of the mail which I ran overnight and it seems now I am getting related emails again. I'll test for a few more days and then I'm happy to close the ticket if that's ok with you?

For reference:

    10:14:46 [alex@zen:~/s/emacs] $ du -sh ~/Maildir
    55G     /home/alex/Maildir
    10:15:09 [alex@zen:~/s/emacs] $ du -sh ~/.cache/mu/
    46G     /home/alex/.cache/mu/
    10:15:19 [alex@zen:~/s/emacs] $ mu info
    maildir           : /home/alex/Maildir
    database-path     : /home/alex/.cache/mu/xapian
    schema-version    : 451
    max-message-size  : 100000000
    batch-size        : 250000
    messages in store : 4582346
    created           : Tue 30 Mar 2021 22:25:33 BST
    personal-address  : alex.bennee@linaro.org

**Comment by stsquad** [comment]
Hmm I spoke too soon. It seems the inability to see related emails applies to all emails that have arrived since I did a full re-init. To illustrate, without a date range limit:

    4745042�  12:25:40     ✔                 Alex Bennée            Re: [PATCH for-6.0 0/2] document gdbstub debugging of multicore machines
    �4716351�  10:40:06     ✔                 Alex Bennée            Re: Fwd: Linaro virtio-SCMI demo
    �4716352�  10:36:35     ✔                 Alex Bennée            Re: Fwd: Virtio demo
    �1684�  Mon 29/03/21 ✔                 Alex Bennée            [PATCH for 6.0-rc2? v1 0/6] check-tcg for non-x86 hosts
    �1372�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 3/6] tests/tcg: add concept of container_hosts
    �724�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 4/6] tests/tcg/configure.sh: make sure we pick up x86_64 cross compilers
    �3676818�  Mon 29/03/21 ✱⎕                no-reply@patchew.org   │ Re: [PATCH for 6.0-rc2? v1 0/6] check-tcg for non-x86 hosts
    �938�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 1/6] tests/tcg: update the defaults for x86 compilers
    �133936�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 1/6] tests/tcg: update the defaults for x86 compilers
    �984�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �112473�  Mon 29/03/21 ✔                 Thomas Huth            │ │ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �139354�  Mon 29/03/21 ✔                 Willian Rampazzo       │ │ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �102514�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �2151�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �141292�  Mon 29/03/21 ✔                 Thomas Huth            │ │ Re: [PATCH v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �90040�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �12908�  Mon 29/03/21 ✔                 Alex Bennée            └ [PATCH  v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �97668�  Tue 30/03/21 ❮✔                Richard Henderson        └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �11425�  Tue 30/03/21 ✔                 Alex Bennée                └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �103045�  Tue 30/03/21 ✔                 Richard Henderson            └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �126616�  Tue 30/03/21 ✔                 Peter Maydell                  └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �4582368�  Tue 30/03/21 ✔                 Richard Henderson                └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �1657�

and adding the date: limiter

    �48290�  Thu 25/03/21 ❮✔                Peter Maydell          [PATCH for-6.0 0/2] document gdbstub debugging of multicore machines
    �45872�  Thu 25/03/21 ✔                 Peter Maydell          │ [PATCH for-6.0 1/2] docs/system/gdb.rst: Add some more heading structure
    �19502�  Thu 25/03/21 ✔                 Peter Maydell          │ [PATCH for-6.0 2/2] docs/system/gdb.rst: Document how to debug multicore machines
    �37327�  Thu 25/03/21 ✔                 Philippe Mathieu-Daudé │ Re: [PATCH for-6.0 0/2] document gdbstub debugging of multicore machines
    �4745042�  12:25:40     ✔                 Alex Bennée            └ Re: [PATCH for-6.0 0/2] document gdbstub debugging of multicore machines
    �4745043�  12:25:56     ✔                 Philippe Mathieu-Daudé   └ Re: [PATCH for-6.0 0/2] document gdbstub debugging of multicore machines
    �4716337�  08:08:14     ❮✔                Mike Holmes            Fwd: Virtio demo
    �4716352�  10:36:35     ✔                 Alex Bennée            └ Re: Fwd: Virtio demo
    �4716358�  10:44:31     ✔                 Mike Holmes              └ Re: Fwd: Virtio demo
    �4716336�  08:08:43     ❮✔                Mike Holmes            Fwd: Linaro virtio-SCMI demo
    �4716351�  10:40:06     ✔                 Alex Bennée            └ Re: Fwd: Linaro virtio-SCMI demo
    �4716354�  10:43:26     ✔                 Mike Holmes              └ Re: Fwd: Linaro virtio-SCMI demo
    �1684�  Mon 29/03/21 ✔                 Alex Bennée            [PATCH for 6.0-rc2? v1 0/6] check-tcg for non-x86 hosts
    �1372�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 3/6] tests/tcg: add concept of container_hosts
    �724�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 4/6] tests/tcg/configure.sh: make sure we pick up x86_64 cross compilers
    �3676818�  Mon 29/03/21 ✱⎕                no-reply@patchew.org   │ Re: [PATCH for 6.0-rc2? v1 0/6] check-tcg for non-x86 hosts
    �938�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 1/6] tests/tcg: update the defaults for x86 compilers
    �133936�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 1/6] tests/tcg: update the defaults for x86 compilers
    �984�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �112473�  Mon 29/03/21 ✔                 Thomas Huth            │ │ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �139354�  Mon 29/03/21 ✔                 Willian Rampazzo       │ │ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �102514�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 2/6] tests/docker: don't set DOCKER_REGISTRY on non-x86_64
    �2151�  Mon 29/03/21 ✱⎕                Alex Bennée            │ [PATCH  v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �141292�  Mon 29/03/21 ✔                 Thomas Huth            │ │ Re: [PATCH v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �90040�  Tue 30/03/21 ✔                 Richard Henderson      │ └ Re: [PATCH v1 5/6] tests/tcg/i386: expand .data sections for system tests
    �12908�  Mon 29/03/21 ✔                 Alex Bennée            └ [PATCH  v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �97668�  Tue 30/03/21 ❮✔                Richard Henderson        └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �11425�  Tue 30/03/21 ✔                 Alex Bennée                └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �103045�  Tue 30/03/21 ✔                 Richard Henderson            └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �126616�  Tue 30/03/21 ✔                 Peter Maydell                  └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �4582368�  Tue 30/03/21 ✔                 Richard Henderson                └ Re: [PATCH v1 6/6] tests/i386/test-i386: try and correct constrain 16 bit call (WIP)
    �1657�

The check-tcg thread was from Monday and I hadn't replied since. You can see I replied to some emails today but the rest of the thread context (from today or earlier in the month) doesn't show up until I date limit it.

**Comment by stsquad** [comment]
@djcb sorry finger trouble, mouse hit the wrong button,

**Comment by nicolasavru** [comment]
I think I see what's happening here (and in #1911 and #1972), but I don't understand what xapian is doing here.

My understanding of the desired algorithm when using threads and include-related:
1. Run the user's query with maxnum, so returning n results.
2. Find the set of all messages related to the result from step 1. This will return m >= n results.
3. Calculate threads on the result from step 2. This will return the same m results as step 2.

What we're doing now is:
1. Run the user's query with maxnum, so returning n results (maybe, see my comments about xapian below).
2. Find the set of all messages related to the result from step 1, but also oring in the original query without maxnum, getting a lot more results than desired.
3. Calculate threads on the result from step 2, but enforcing the maxnum limit here, resulting us throwing away a lot of messages that should've been kept for threads because they were crowded out by the query in step 2 (and by each other, I don't think we should be enforcing maxnum past step 1 at all). This also explains why limiting the user query to a narrow time range improves things.

So I'd expect the following changes are necessary:
1. mu-query.cc:195: sort by date instead of sortfieldid and pass the descending qflag (probably just or qflags into lead_qflags on line 190).
2. mu-query.cc:111: the set of thread_ids (or thread_ids plus message ids?) should, by construction, also contain every message from the user's query, so we don't need to include the original query here again. This is actually wrong because now we're re-running the original query without maxnum.
3. mu-query.cc:175 and 210: not pass maxnum to run_threading.
4. mu-query.cc:139-145 and mu-match-deciders.cc:203-231: I don't understand why we're re-querying as part of threading at all. We shouldn't need to get anything more from xapian.

I tried making the changes above (except for 4), but things don't work as expected; the maxitems argument for get_mset seems to just... not work: the decider is being called a lot more than maxnum times and the number of documents returned also varies depending on whether descending is true or false (propagating through to maybe_sort). I tried manually limiting the result of the query to m results in the match deciders, but that just breaks things even more.

So looks like these issues were introduced by the switch to the xapian/mset/match decider machinery in 95dffb98a637c54129404cb50edd67b456fa4f43.

**Comment by djcb** [comment]
Ah, thanks for the analysis, that provides some ways to attack this problem; we should finally get to the bottom of this...

What I think  is happening is that the match-decider gets _all_ matches (regardless of the maxnum), since its very job is to decide which matches will in that maxnum-sized mset. We get the message-ids of the messages this first mset (the "leader" set) as a side-effect of that match-decider, and use those to determine the related messages.

But since that match-deciding indeed considers _all_ matching (regardless of maxnum), these are too many... we'd like to get the message-ids of just those messages which are in the "leader" mset. So I guess we need to gather the message-ids in a different way...

I have push a change that does that, that should make a difference for that part at least.

**Comment by djcb** [comment]
BTW, does the ^^^ help with this problem?

**Comment by nicolasavru** [comment]
Don't think so.

Testing steps (as much for future me as for anyone else testing this): search for a contact (email address) with whom you communicate a lot, say more than 500 emails (the default maxnum). Find a thread where they are present (to/from/cc) in a couple emails, but not most of the thread.

Expected result: that entire thread is present, including the emails in which the contact was not present. Have more than 500 total results: 500 emails including the searched-for contact, plus additional emails which got pulled in due to being in threads.

Actual result: only the couple emails in which the searched-for contact was directly present are returned, the rest of the thread (both before and after) is not present. There are exactly 500 results.

**Comment by nicolasavru** [comment]
I think #2048 fixes this (and #1911). #1972 is not obviously fixed by this, but maybe that got fixed incidentally, I haven't tried to repro it.

From my earlier comment:
> mu-query.cc:139-145 and mu-match-deciders.cc:203-231: I don't understand why we're re-querying as part of threading at all. We shouldn't need to get anything more from xapian

Looking at this again, I think xapian is just being used to sort the threads (top-level messages, thread leaders) there. I would imagine it would be faster to sort them directly, without delegating that to a xapian query, but I haven't benchmarked both options yet, so I haven't touched that for now. Either way, I think the code is correct.

**Comment by djcb** [comment]
Oh, cool! It makes sense.... I'll try this.

As for the sorting, yeah, we need Xapian as it's the only way to get a sorted `Xapian::Mset`; we could instead "materialize" the documents (= messages) a bit earlier, and sort those, but that's not necessarily faster (with the Xapian::Met we only need to materialize the subset we need).
