### ISSUE TITLE
Glib-critical 

### ISSUE THREAD

**Issue by Airwan** [djcb/mu#2230]
## Expected or desired behavior

mu find result show the message date correctly.

## Actual behavior

I have a line like the following in place of the date :

(mu:7484): GLib-CRITICAL **: 03:49:00.236: g_date_time_format: assertion 'g_utf8_validate (format, -1, NULL)' failed
xxx@email.com subject (are ok)

## Steps to reproduce

Fresh install from git
mu init and mu index, 
then mu find "flag:unread" and all results appears  with that line.

## Versions of mu, mu4e/emacs, operating system etc.

mu4e 1.7.12 / Ubuntu 20.04 uptodate

**Comment by djcb** [comment]
Hmm, that's not good. I'm unable to reproduce though, so perhaps it's some library version issue.

**Comment by ReneFroger** [comment]
I'm having the same issue on a fresh install of Mu with newly imported Gmail mal files. When I do `mu find XXX` and then I see the relevant results, accompanied with each other with this error message: 

```
(mu:1418632): GLib-CRITICAL ** g_date_time_format: assertion 'g_utf8_validate (format, -1, NULL)' failed
```

**Comment by djcb** [comment]
Does e.g.:
```
LANG=en_US.UTF-8 mu find hello
```
work (assuming you have that installed)?

**Comment by ReneFroger** [comment]
Same result unfortunately. 
Even exporting `LANG=en_US.UTF-8` to my shell didn't made any difference. 
`echo $LANG` gave me  `en_US.UTF-8` as output.

**Comment by ReneFroger** [comment]
Perhaps relevant, but these errors are not visible when I search in my mails with mu4e inside Emacs. Then the results are showing up without being accompanied with errors like in shell.

**Comment by ReneFroger** [comment]
This bugtracker might be relevant, it is talking about the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=833117

**Comment by djcb** [comment]
> This bugtracker might be relevant, it is talking about the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=833117

"Does not disable glib slice allocator with glib >= 2.35. Startup warning."

That doesn't seem related. Am I missing something?

**Comment by ReneFroger** [comment]
After giving a closer look, it's not very related indeed. My bad. I'm still figuring out where all these errors came from.

**Comment by djcb** [comment]
I've pushed a change with should give a little more information when this problem happens. If you see a new warning, let me know!

**Comment by Airwan** [comment]
Sorry for the delay. The new message are : 

** (mu:187711): CRITICAL **: 22:57:20.084: time_to_string: non-utf8 format ()

So I have now the time, but still an issue.

At compile time I have : 

../lib/utils/mu-utils.cc: In destructor ‘Mu::TempDir::~TempDir()’:
../lib/utils/mu-utils.cc:622:10: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  622 |  ::system(cmd.c_str());
      |  ~~~~~~~~^~~~~~~~~~~~~
Don't know if it is relevant. 

Many thanks for your works!

**Comment by fab4100** [comment]
I am getting the same behavior. This may be related: [https://patchwork.kernel.org/project/qemu-devel/patch/20220424103120.284688-1-haiyue.wang@intel.com/](https://patchwork.kernel.org/project/qemu-devel/patch/20220424103120.284688-1-haiyue.wang@intel.com/)

**Comment by fab4100** [comment]
_**Update:**_ a (meson) debug build parses the date correctly

**Comment by djcb** [comment]
The problem appears to be outside mu... I've added a workaround for now. 

Not much more we can do, so closing this.
