### ISSUE TITLE
[mu4e bug] Marking a message in single-window mode opens the next message although it shouldn't

### ISSUE THREAD

**Issue by tmalsburg** [djcb/mu#2385]
**Describe the bug**

Marking a message in single-window mode opens the next message although it shouldn't. It does not always happen, but so far I couldn't figure out under what conditions it does and doesn't happen.  It definitely happens most of the times.

**How to Reproduce**

`(setq mu4e-split-view 'single-window)`, then open headers-view and flag a message (or mark for something else). First, it works when I start a new session, but after having opened a message and closing it again, it happens pretty reliably, although there seems to be some sequence of actions that can temporarily revert it to working correctly. 

**Environment**
Ubuntu 22.04, Emacs 29.0.50 from git, mu4e from git (pulled two days ago).

**Checklist**
- [X] you are running either the latest 1.6.x release, or a 1.8.x release (otherwise, please upgrade)
- [X] you are running mu4e without any third-party extensions (otherwise, make sure you can reproduce without those)
- [X] you have read all of the above

**Comment by tmalsburg** [comment]
Update: I can only trigger this bug when `*mu4e-headers*` is the only window in the frame. (Haven't tested with multiple frames.) When there is another window, I wasn't able to trigger it.

**Comment by djcb** [comment]
There was an issue with the marking when in single-window mode (I've pushed a fix); but advancing to the next message is a defcustom `mu4e-headers-advance-after-mark`.  Not sure if we followed that earlier, but we do so now.

**Comment by tmalsburg** [comment]
> There was an issue with the marking when in single-window mode (I've pushed a fix);

Thank you, Dirk,  Unfortunately, the issue persists in the latest version.  It's actually a bit worse because now it also happens then I have multiple windows.  As before, it works initially, but no longer after having opened and closed a message.

> but advancing to the next message is a defcustom mu4e-headers-advance-after-mark. Not sure if we followed that earlier, but we do so now.

Yes, moving to the next message is desired and consistent with earlier behavior.

**Comment by djcb** [comment]
In split-view mode `horizontal`, marking a message opens the next one (with default settings), and the same thing happens when I try with split-view, and that seems a reasonable behavior. But what different behavior are you expecting?

**Comment by tmalsburg** [comment]
I expect the same behavior that we had before the recent changes: When I mark a message, point moves to the next line in headers view and nothing else happens.  Consider this scenario: I want to mark 5 messages for deletion in single-window mode:

1. Mark the first -> open 1st message
2. Close 1st message
3. Mark the second -> opens 2nd message 
4. Close 2nd message
5. ...

So I have to open and close 5 messages just to mark them for deletion.  That's clearly not something that any user would want.

**Comment by tmalsburg** [comment]
> and the same thing happens when I try with split-view

Clarification: do you mean single-window above instead split-view? I'm asking because this issue is about single-window not about the split-view configuration.

**Comment by tmalsburg** [comment]
I think this may have caused confusion:

>  It's actually a bit worse because now it also happens when I have multiple windows.

What I mean by "multiple windows" is not horizontal or vertical mu4e configuration, but simply that there is some other unrelated Emacs window displaying a non-mu4e buffer.

**Comment by djcb** [comment]
So, I'm trying to understand:
1. this is _not_ about `(setq 'mu4e-split-view 'single-window)`, but some other way of using a single window? 
2. but then, when in try with 1.8, and read messages, I press `D`, the message is marked for deletion and we move to the next. So seems the behavior didn't change?

So what am I missing?

**Comment by tmalsburg** [comment]
First of all: Happy Christmas, and thank you for mu/mu4e which make my work more enjoyable/bearable almost every single day of the year. Sent from my iPhoneOn 25. Dec 2022, at 07:48, Dirk-Jan C. Binnema ***@***.***> wrote:﻿
So, I'm trying to understand:

this is not about (setq 'mu4e-split-view 'single-window), but some other way of using a single window?My understanding is that we’re talking about pretty standard use of single-window. I.e. there is one window with headers, when you press enter, that same window shows the message, and so on. 
but then, when in try with 1.8, and read messages, I press D, the message is marked for deletion and we move to the next. So seems the behavior didn't change?That’s not the behavior that I’m getting. I hit d for delete in headers view, the headers view is replaced with the next message. That’s different from the old behavior where, d would just mark for deletion and move to the next message *in* headers view. I think the bug is perhaps just not triggered in your setup. As I explained above, I cal also not reliably trigger it but it happens in 90% of cases. It seems to depend on some state information. 

So what am I missing?

**Comment by djcb** [comment]
AHa, happy :christmas_tree: all :)

So to summarize, we _are_ talking about `mu4e-split-view` set to `'single-window'. In 1.8.x _and_ 1.9.x, the behavior after marking is governed by  `mu4e-headers-advance-after-mark`, and that seems to work.

But, the issue is about what `mu4e-headers-advance-after-mark` _means_? I.e, should it _only_ move the pointer to next message or also _open_ that next message? In my case, it always opens the next message (in 1.8.13 as well as 1.9.x), and in your case(s) it did _not_ open it in the 1.8.13 (and early 1.9.x) ?  As I said, in my case, it always opens.

Regardless, perhaps we can restore the alternative behavior, but  it seems utterly confusing/error-prone marking messages without knowing _what_ you are marking, or?

**Comment by theophilusx** [comment]
"Dirk-Jan C. Binnema" ***@***.***> writes:

> AHa, happy 🎄 all :)
>
> So to summarize, we are talking about mu4e-split-view set to 'single-window'. In 1.8.x _and_ 1.9.x, the behavior after marking
> is governed by mu4e-headers-advance-after-mark`, and that seems to work.
>
> But, the issue is about what mu4e-headers-advance-after-mark means? I.e, should it only move the pointer to next message or also open
> that next message? In my case, it always opens the next message (in 1.8.13 as well as 1.9.x), and in your case(s) it did not open it in the 1.8.13
> (and early 1.9.x) ? As I said, in my case, it always opens.
>
> Regardless, perhaps we can restore the alternative behavior, but it seems utterly confusing/error-prone marking messages without knowing
> what you are marking, or?
>

I think there is something a little more subtle going on. I've noticed
that when I am in the headers view, open a message and hit 'q' to leave
the message (returning to the header view) and, after having marked a
few messages for delete, when I hit 'x' to execute the message marks, a
message view buffer for a previously viewed (and often now deleted
i.e. no longer shows up in the headers view) message is displayed (the
header view is split as would be the case when you view the message and
the cursor is in the message/article buffer, not the header view
buffer).

This doesn't always seem to happen, but is happening most of the
time. Really still trying to narrow down to the precise reproducible
case.
).

**Comment by djcb** [comment]
Ah, seems mu4e-view-quit must reset mu4e~headers-view-win; I've pushed a fix for that.

**Comment by djcb** [comment]
Oh, and another change to revive the "mini-menu" instead of the main-buffer, when in `split-window` mode.

**Comment by mickeynp** [comment]
@djcb, sorry I only just now saw this issue. (Just tag me if there are buffer/window issues and I'll chip in and help.)

I do think we should consider replacing `mu4e~headers-view-win` with a function. It'd avoid a lot of state issues that can happen.

**Comment by tmalsburg** [comment]
Just to confirm, it's fixed on my system as well.  Thanks everyone.
